copy-game: echo game ID

diff --git a/copy-game b/copy-game
--- a/copy-game
+++ b/copy-game
@@ -2,18 +2,21 @@
 
 # Copy results of a game to clipboard in the form GUESSES => ANSWER
 
-if [ -n "$1" ]; then
-    if ! line="$(grep "$1:" games.md)"; then
-        echo "Can't find '$1'"
+game="$1"
+if [ -n "$game" ]; then
+    if ! line="$(grep "$game:" games.md)"; then
+        echo "Can't find '$game'"
         exit 1
     fi
 else
     line="$(tail -1 games.md)"
+    # shellcheck disable=SC2016
+    game="$(echo "$line" | sed -E 's/^\* ([0-9]+):.*$/\1/')"
 fi
 
 # shellcheck disable=SC2016
 result="$(echo "$line" | sed -E 's/^\* ([0-9]+): `([^`]+)` ([^ ]+) `([^`]+)`$/\2 => \4/')"
-echo "$result"
+echo "$game: $result"
 
 if [ "$(uname)" == "Linux" ]; then
     echo "$result" | wl-copy
